local: False
local_paths:
  noise: ""
  data: ""
remote_paths:
  noise: "/media/mark/extradrive2/uncertain_inversion/environmental_data/noise/sbcex22_noise.h5"
  data: "/media/mark/extradrive2/uncertain_inversion/single_sensor_spectrum_RI/sim_data"